spring.datasource.url=jdbc:postgresql://dpg-d814d6j7uimc7381h6og-a.oregon-postgres.render.com:5432/moneymanager_suraj_y9gd

spring.datasource.username=moneymanager_suraj_y9gd_user
spring.datasource.password=aRFgnCHvZozs8RF2WxwSM0lWNhJZM8zu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true