# Data Source Settings
spring.datasource.url=jdbc:postgresql://dpg-d822tt83kofs73dsfb0g-a.singapore-postgres.render.com/money_manager_4d5v?sslmode=require
spring.datasource.username=money_manager_4d5v_user
spring.datasource.password=ubXvXnq0VntJnb9dypkgzhOM6jHI7Ugg
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# 'update' is fine for a project, but ensures it speaks PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Show complete stack traces
logging.level.root=DEBUG
logging.level.com.moneymanagerproject=TRACE
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE

# Show full error response
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
server.error.include-binding-errors=always

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false