spring.datasource.url=jdbc:postgresql://dpg-d814d6j7uimc7381h6og-a.oregon-postgres.render.com/moneymanager_suraj_y9gd
spring.datasource.username=moneymanager_suraj_y9gd_user
spring.datasource.password=aRFgnCHvZozs8RF2WxwSM0lWNhJZM8zu
